-- MySQL Script generated by MySQL Workbench
-- Чт. 28 янв. 2016 20:34:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yii1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yii1` ;

-- -----------------------------------------------------
-- Schema yii1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yii1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `yii1` ;

-- -----------------------------------------------------
-- Table `yii1`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yii1`.`user` ;

CREATE TABLE IF NOT EXISTS `yii1`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(128) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `surname` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `salt` VARCHAR(255) NOT NULL COMMENT '',
  `access_token` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `access_token_UNIQUE` (`access_token` ASC)  COMMENT '')
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `yii1`.`calendar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `text` TEXT NOT NULL COMMENT '',
  `creator` INT NOT NULL COMMENT '',
  `date_event` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_note_1_idx` (`creator` ASC)  COMMENT '',
  CONSTRAINT `fk_note_1`
  FOREIGN KEY (`creator`)
  REFERENCES `yii1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `yii1`.`access` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_owner` INT NOT NULL COMMENT '',
  `user_guest` INT NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_access_1_idx` (`user_owner` ASC)  COMMENT '',
  INDEX `fk_access_2_idx` (`user_guest` ASC)  COMMENT '',
  CONSTRAINT `fk_access_1`
  FOREIGN KEY (`user_owner`)
  REFERENCES `yii1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_2`
  FOREIGN KEY (`user_guest`)
  REFERENCES `yii1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `yii1`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `text` TEXT NOT NULL COMMENT '',
  `creator` INT NOT NULL COMMENT '',
  `date_create` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_note_1_idx` (`creator` ASC)  COMMENT '',
  CONSTRAINT `fk_note_1`
  FOREIGN KEY (`creator`)
  REFERENCES `yii1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
